name: persistent_homology
channels:
  - defaults
dependencies:
  - cython=0.29.6
  - pyqtgraph=0.10.0
  - python=3.7.1
  - pandas=0.24.2
  - matplotlib=3.0.3
  - numpy=1.16.2
  - networkx=2.2
  - scipy=1.2.1
